### ISSUE TITLE
About the article

### ISSUE THREAD

**Issue by vladislavivanistsev** [grimme-lab/dxtb#161]
The work is great, but please do not overuse the AI in writing your articles.
Your abstract in https://doi.org/10.1063/5.0216715 is full of words and constructions that only AI uses. For example, for me markers are "leveraging" and "streamlines".

**Comment by marvinfriede** [comment]
Thanks. I am putting in a lot of (manual) effort into improving the language and vocabulary of my manuscripts. And while I ran parts of the final version through AI to help improve wording, avoid word repetitions, etc., I am pretty sure these so called "marker words" were already in the manuscript before that.

There is also a big discussion about the word "delve" being a sign of AI. However, as with probably most words, some people use it regularly and believe there is nothing special about it.  

Finally, I want to emphasize again that I never used AI to create new content, but only to reword existing text.
