### ISSUE TITLE
Units of positions and energy

### ISSUE THREAD

**Issue by njzjz** [grimme-lab/dxtb#167]
Hi, I am wondering what the units of positions and energy are. I don't find such information either in README or in the documentation.

**Comment by marvinfriede** [comment]
Everything is in atomic units. I will add this information to the docs. Thanks for the hint.

In case you are working with coordinate files, there are also reader functions. See [this example](https://github.com/grimme-lab/dxtb/blob/main/examples/forces.py) from the repo or [these examples](https://github.com/tad-mctc/tad-mctc/tree/main/examples/read).

**Comment by marvinfriede** [comment]
If you need to convert units, we have some basic tools in the `tad_mctc` dependency. You can use it like this:

```python
from tad_mctc import units

onebohr = 1
print(f"{onebohr} bohr is equal to {onebohr*units.AU2AA} Angstrom.")
```
