### ISSUE TITLE
Are spin-polarized (sp)GFNn-xTB calculations supported?

### ISSUE THREAD

**Issue by MauriceDHanisch** [grimme-lab/dxtb#174]
Hi, thank you for your work! 

I wanted to ask whether spin-polarized calculations as described in the [documentation](https://xtb-docs.readthedocs.io/en/latest/spgfn.html) of tblite are supported, or if there are plans to include this feature in a future release.

**Comment by marvinfriede** [comment]
Currently, they are not supported.

We might add this feature in the future, but it requires some additional work (because we don't have a true unrestricted implementation with a second spin channel as in tblite yet).

**Comment by MauriceDHanisch** [comment]
Thank you for the quick response!
