### ISSUE TITLE
Energy Calculation Discrepancy Between CLI and Python Interface for GFN1 Method on C₂O₄²⁻

### ISSUE THREAD

**Issue by ivan-pikulin** [grimme-lab/dxtb#185]
When calculating the energy of the C₂O₄²⁻ particle using the GFN1 method through the CLI, I obtain an energy value of E = -23.36859787394582 Eh:
```
dxtb C2O4_2-.xyz --chrg -2 --method gfn1
```
This result is consistent with the original xtb output. However, when running the calculation via Python 3.8.20, the energy value differs significantly: E = -10.23310868335979 Eh.

Here’s the Python code used:
```python
import torch
from dxtb.calculators import GFN1Calculator

dd = {"dtype": torch.float64}
numbers = torch.tensor([8, 6, 8, 6, 8, 8])
positions = torch.tensor([
    [-0.0267,  1.4251, -0.1981],
    [ 0.2423,  0.1907, -0.1526],
    [ 1.3053, -0.3579, -0.5618],
    [-0.8792, -0.7782,  0.4899],
    [-0.5850, -2.0033,  0.5936],
    [-1.9674, -0.2388,  0.8412]
], **dd)

calc = GFN1Calculator(numbers, **dd)
energy = calc.get_energy(positions, chrg=-2)
print(f"energy: {energy.item()} Eh")
```
I use the dxtb==0.1.1, torch==2.2.2+cu121, the full list of installed dependencies can be found in the file [pip_freeze.txt](https://github.com/user-attachments/files/17572904/pip_freeze.txt)

So, why do the energy calculations differ between the command line and the Python interface?

**Comment by marvinfriede** [comment]
I will take a look. Can you also provide the xyz file?

**Comment by ivan-pikulin** [comment]
> I will take a look. Can you also provide the xyz file?

Of course. I have used this file: [C2O4_2-.xyz.txt](https://github.com/user-attachments/files/17574800/C2O4_2-.xyz.txt) (`.txt` was added as github does not allow .xyz extension)

**Comment by marvinfriede** [comment]
The xyz file is in Angström, but the Python interface has to be in Bohr.

Check out https://github.com/grimme-lab/dxtb/issues/167 for some examples on reading xyz files (there is a convenience function that the CLI also uses) and unit conversion.

In short, you need to multiply you position tensor with the conversion factor.

```python
from tad_mctc.units import AA2AU

positions_au = positions * AA2AU
```
