### ISSUE TITLE
Hi! Wondering are you currently in including GFN2-xtb?

### ISSUE THREAD

**Issue by Yufan121** [grimme-lab/dxtb#186]
Hello, we are developing a XTB + Machine learning method that relies on the derivatives through xTB. However, we notice that only xtb1 is included. To compare results with state-of-the-art, we would really need the GFN2-xtb, and this can save us a great lot of trouble. Just wondering that are you currently in the plan of also including this second generation? :)

**Comment by marvinfriede** [comment]
Yes, we plan to implement GFN2. However, I am currently tied up in another project. I will probably start working in it in January/February.

**Comment by Yufan121** [comment]
Thanks Marvin, thanks so much for the information and wish you luck on your project!
